In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.3.1'

In [3]:
# 判断当前是否在eager模式下
tf.executing_eagerly()

True

In [4]:
x = [[2,]]

In [5]:
# 两个矩阵相乘
m = tf.matmul(x,x)

In [8]:
m.numpy()

array([[4]])

In [9]:
# 使用tensorflow方法建立一个常量
a = tf.constant([[1,2],[3,4]])

In [10]:
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [11]:
a.numpy()

array([[1, 2],
       [3, 4]])

In [18]:
import numpy as np

In [19]:
d = np.array([[5,6],[7,8]])
d

array([[5, 6],
       [7, 8]])

In [21]:
(a+b).numpy()

array([[3, 5],
       [7, 9]])

In [23]:
g = tf.convert_to_tensor(10)

In [24]:
float(g)

10.0

In [13]:
b = tf.add(a,1)

In [14]:
b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]])>

In [15]:
 c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2,  6],
       [12, 20]])>

In [16]:
num = tf.convert_to_tensor(10)
num

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [17]:
for i in range(num.numpy()):
    i = tf.constant(i)
    if int(i%2) == 0:
        print('even')
    else:
        print('odd')

even
odd
even
odd
even
odd
even
odd
even
odd
