In [8]:
import tensorflow as tf

In [9]:
print('tensorflow version:{}'.format(tf.__version__))

tensorflow version:2.3.1


In [10]:
# 建立dataset，使用一维列表建立
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6, 7])

In [11]:
dataset #shape为每一个组件的shape

<TensorSliceDataset shapes: (), types: tf.int32>

In [12]:
# 每个数据都是一个组件，自动转换成为Tensor
for ele in dataset:
    print(ele)  

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)


In [13]:
# 将数据转换成Numopy格式输出
for ele in dataset:
    print(ele.numpy())

1
2
3
4
5
6
7


In [15]:
# 建立dataset，使用二维列表建立
dataset = tf.data.Dataset.from_tensor_slices([[1,2],[3,4],[5,6]])

In [16]:
dataset  #shape为每一个组件的shape

<TensorSliceDataset shapes: (2,), types: tf.int32>

In [18]:
for ele in dataset:
    print(ele.numpy())  

[1 2]
[3 4]
[5 6]


In [22]:
# 建立dataset，使用字典建立
dataset = tf.data.Dataset.from_tensor_slices({'a':[1,2,3,4],
                                              'b':[6,7,8,9],
                                              'c':[12,13,14,15]
                                             })

In [25]:
dataset

<TensorSliceDataset shapes: {a: (), b: (), c: ()}, types: {a: tf.int32, b: tf.int32, c: tf.int32}>

In [26]:
for ele in dataset:
    print(ele)  

{'a': <tf.Tensor: shape=(), dtype=int32, numpy=1>, 'b': <tf.Tensor: shape=(), dtype=int32, numpy=6>, 'c': <tf.Tensor: shape=(), dtype=int32, numpy=12>}
{'a': <tf.Tensor: shape=(), dtype=int32, numpy=2>, 'b': <tf.Tensor: shape=(), dtype=int32, numpy=7>, 'c': <tf.Tensor: shape=(), dtype=int32, numpy=13>}
{'a': <tf.Tensor: shape=(), dtype=int32, numpy=3>, 'b': <tf.Tensor: shape=(), dtype=int32, numpy=8>, 'c': <tf.Tensor: shape=(), dtype=int32, numpy=14>}
{'a': <tf.Tensor: shape=(), dtype=int32, numpy=4>, 'b': <tf.Tensor: shape=(), dtype=int32, numpy=9>, 'c': <tf.Tensor: shape=(), dtype=int32, numpy=15>}


In [42]:
import numpy as np

In [43]:
# 使用Numpy来创建dataset
dataset = tf.data.Dataset.from_tensor_slices(np.array([1,2,3,4,5,6,7]))

In [44]:
for ele in dataset:
    print(ele.numpy())

1
2
3
4
5
6
7


In [45]:
# 取出前4个数
for ele in dataset.take(4):
    print(ele.numpy())

1
2
3
4


In [46]:
next(iter(dataset.take(1))) # 取第一个数

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [49]:
# 乱序：全部乱序，参数为数据长度
dataset = dataset.shuffle(7)
# 重复：count指定重复次数
dataset = dataset.repeat(count = 2)
# 将数据分批次：默认参数为batch_size指定每个批次大小
dataset = dataset.batch(3)

In [50]:
for ele in dataset:
    print(ele.numpy())

[5 4 6]
[2 1 4]
[2 7 3]
[7 3 1]
[6 5 4]
[7 6 1]
[6 3 3]
[2 7 5]
[1 4 2]
[5]


In [51]:
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6, 7])

In [52]:
# 使用函数---将每个数据都进行平方
dataset = dataset.map(tf.square)

In [53]:
for ele in dataset:
    print(ele.numpy())

1
4
9
16
25
36
49
